name: Generate Snake

on:
  push:
    branches:
      - master  # or the default branch of your repository
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: p-medeiros  # Replace with your GitHub username
          svg_out_path: dist/snake.svg

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate snake"
          branch: master  # or the default branch of your repository
          file_pattern: dist/snake.svg
